// Generated by scripts/gen-opencode.sh: edit the heredoc there, not this file.
//
// OpenCode adapter for the plugin's PostToolUse hooks. No check lives here.
// After a write or edit it rebuilds the payload Claude Code would have sent,
// runs every command hooks.json declares for that tool, and appends what a
// hook reports to the tool output the model reads. The shell scripts stay
// the one implementation for both harnesses.
//
// Loaded from ~/.config/opencode/plugins/ (install-opencode.sh links it
// there). Run directly with an event on stdin to see what a hook would add:
//   printf '{"tool":"write","args":{"filePath":"/tmp/x.md","content":"a"},"output":""}' \
//     | node 10x-hooks.js
import { spawnSync } from "node:child_process";
import { readFileSync, realpathSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// The installer links this file into the config tree, so the plugin root is
// found from the real location: opencode/plugins/ sits beside plugins/10x/.
const SELF = realpathSync(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = resolve(dirname(SELF), "..", "..", "plugins", "10x");
const MANIFEST = join(PLUGIN_ROOT, "hooks", "hooks.json");

// OpenCode tool id to Claude Code tool name, and the argument names the
// hooks read (lib.sh: file_path, content, old_string, new_string).
const TOOLS = {
  write: { name: "Write", args: { filePath: "file_path", content: "content" } },
  edit: {
    name: "Edit",
    args: { filePath: "file_path", oldString: "old_string", newString: "new_string" },
  },
};

function payloadFor(tool, args) {
  const spec = TOOLS[tool];
  if (!spec || !args || typeof args !== "object") return null;
  const toolInput = {};
  for (const [from, to] of Object.entries(spec.args)) {
    if (args[from] !== undefined) toolInput[to] = args[from];
  }
  return { tool_name: spec.name, tool_input: toolInput };
}

// The PostToolUse commands of hooks.json whose matcher names this tool,
// verbatim: ${CLAUDE_PLUGIN_ROOT} is expanded by the shell, as under Claude
// Code, so the manifest stays the only place a hook is declared.
function commandsFor(toolName) {
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
  } catch (err) {
    console.error(`10x hooks: cannot read ${MANIFEST}: ${err.message}`);
    return [];
  }
  const commands = [];
  for (const group of manifest.hooks?.PostToolUse ?? []) {
    if (group.matcher && !new RegExp(`^(?:${group.matcher})$`).test(toolName)) continue;
    for (const hook of group.hooks ?? []) {
      if (hook.type === "command" && hook.command) commands.push(hook.command);
    }
  }
  return commands;
}

// What a hook reports, under Claude Code's contract: exit 2 sends stderr
// back to the model; exit 0 with a JSON hookSpecificOutput adds its
// additionalContext. Anything else is for the user's log, not the model.
function reportOf(command, payload, cwd) {
  const run = spawnSync("sh", ["-c", command], {
    input: JSON.stringify(payload),
    cwd,
    encoding: "utf8",
    env: { ...process.env, CLAUDE_PLUGIN_ROOT: PLUGIN_ROOT, CLAUDE_PROJECT_DIR: cwd },
  });
  if (run.error) {
    console.error(`10x hooks: ${command}: ${run.error.message}`);
    return "";
  }
  if (run.status === 2) return run.stderr.trim();
  if (run.stderr.trim()) console.error(`10x hooks: ${command}: ${run.stderr.trim()}`);
  if (run.status !== 0) return "";
  try {
    const context = JSON.parse(run.stdout)?.hookSpecificOutput?.additionalContext;
    return typeof context === "string" ? context.trim() : "";
  } catch {
    return "";
  }
}

async function afterTool(input, output, cwd) {
  const payload = payloadFor(input.tool, input.args);
  if (!payload) return;
  for (const command of commandsFor(payload.tool_name)) {
    const text = reportOf(command, payload, cwd);
    if (text) output.output += `\n\n[10x hook ${basename(command)}] ${text}`;
  }
}

export const TenXHooks = async ({ directory }) => ({
  "tool.execute.after": (input, output) => afterTool(input, output, directory),
});

// Direct invocation (node or bun): one event on stdin, the tool output the
// model would read on stdout. This is what test-hooks.sh --harness opencode
// drives; OpenCode itself imports the module and never reaches this branch.
let direct = false;
try {
  direct = realpathSync(process.argv[1] ?? "") === SELF;
} catch {
  direct = false;
}
if (direct) {
  const event = JSON.parse(readFileSync(0, "utf8"));
  const output = { title: "", output: event.output ?? "", metadata: {} };
  await afterTool({ tool: event.tool, args: event.args }, output, process.cwd());
  process.stdout.write(output.output);
}
