// Generated by scripts/gen-opencode.sh: edit the heredoc there, not this file.
//
// OpenCode adapter for the plugin's PostToolUse hooks. No check lives here.
// After a write or edit it rebuilds the payload Claude Code would have sent,
// runs every command hooks.json declares for that tool, and appends what a
// hook reports to the tool output the model reads. The shell scripts stay
// the one implementation for both harnesses.
//
// OpenCode 2.x plugin contract: the module default-exports { id, setup }, and
// setup subscribes with ctx.tool.hook("execute.after", ...). The pre-2.0 shape
// (a named export returning a "tool.execute.after" map) no longer loads.
//
// Loaded from ~/.config/opencode/plugins/ (install-opencode.sh links it
// there). Run directly with an event on stdin to see what a hook would add:
//   printf '{"tool":"write","args":{"filePath":"/tmp/x.md","content":"a"},"output":""}' \
//     | node 10x-hooks.js
import { spawnSync } from "node:child_process";
import { readFileSync, realpathSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// The installer links this file into the config tree, so the plugin root is
// found from the real location: opencode/plugins/ sits beside plugins/10x/.
const SELF = realpathSync(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = resolve(dirname(SELF), "..", "..", "plugins", "10x");
const MANIFEST = join(PLUGIN_ROOT, "hooks", "hooks.json");

// OpenCode tool id to Claude Code tool name, and the argument names the
// hooks read (lib.sh: file_path, content, old_string, new_string). The path
// argument is `path` in OpenCode 2.x and was `filePath` before it, so both
// spellings are accepted: the first one present wins.
const TOOLS = {
  write: { name: "Write", args: { path: "file_path", filePath: "file_path", content: "content" } },
  edit: {
    name: "Edit",
    args: {
      path: "file_path",
      filePath: "file_path",
      oldString: "old_string",
      newString: "new_string",
    },
  },
};

function payloadFor(tool, input) {
  const spec = TOOLS[tool];
  if (!spec || !input || typeof input !== "object") return null;
  const toolInput = {};
  for (const [from, to] of Object.entries(spec.args)) {
    if (input[from] !== undefined && toolInput[to] === undefined) toolInput[to] = input[from];
  }
  if (toolInput.file_path === undefined) return null;
  return { tool_name: spec.name, tool_input: toolInput };
}

// The PostToolUse commands of hooks.json whose matcher names this tool,
// verbatim: ${CLAUDE_PLUGIN_ROOT} is expanded by the shell, as under Claude
// Code, so the manifest stays the only place a hook is declared.
function commandsFor(toolName) {
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
  } catch (err) {
    console.error(`10x hooks: cannot read ${MANIFEST}: ${err.message}`);
    return [];
  }
  const commands = [];
  for (const group of manifest.hooks?.PostToolUse ?? []) {
    if (group.matcher && !new RegExp(`^(?:${group.matcher})$`).test(toolName)) continue;
    for (const hook of group.hooks ?? []) {
      if (hook.type === "command" && hook.command) commands.push(hook.command);
    }
  }
  return commands;
}

// What a hook reports, under Claude Code's contract: exit 2 sends stderr
// back to the model; exit 0 with a JSON hookSpecificOutput adds its
// additionalContext. Anything else is for the user's log, not the model.
function reportOf(command, payload, cwd) {
  const run = spawnSync("sh", ["-c", command], {
    input: JSON.stringify(payload),
    cwd,
    encoding: "utf8",
    env: { ...process.env, CLAUDE_PLUGIN_ROOT: PLUGIN_ROOT, CLAUDE_PROJECT_DIR: cwd },
  });
  if (run.error) {
    console.error(`10x hooks: ${command}: ${run.error.message}`);
    return "";
  }
  if (run.status === 2) return run.stderr.trim();
  if (run.stderr.trim()) console.error(`10x hooks: ${command}: ${run.stderr.trim()}`);
  if (run.status !== 0) return "";
  try {
    const context = JSON.parse(run.stdout)?.hookSpecificOutput?.additionalContext;
    return typeof context === "string" ? context.trim() : "";
  } catch {
    return "";
  }
}

// `event` is OpenCode's execute.after payload: the tool id, the arguments the
// model passed as `input`, and `result`. A failed call carries no result, so
// there is nothing to append to.
//
// What the model reads is result.content, an array of parts; result.output is
// structured data OpenCode only falls back to (JSON-stringified) when content
// is empty. So a report is appended as a text part, and output is left alone:
// concatenating onto output would stringify the object into "[object Object]"
// and destroy the tool result.
async function afterTool(event, cwd) {
  const payload = payloadFor(event.tool, event.input);
  if (!payload || !event.result) return;
  const reports = [];
  for (const command of commandsFor(payload.tool_name)) {
    const text = reportOf(command, payload, cwd);
    if (text) reports.push(`[10x hook ${basename(command)}] ${text}`);
  }
  if (!reports.length) return;
  const result = event.result;
  const parts = Array.isArray(result.content) && result.content.length
    ? [...result.content]
    : [{ type: "text", text: asText(result.output) }];
  result.content = [...parts, { type: "text", text: reports.join("\n\n") }];
}

// The fallback OpenCode itself applies to a non-string output.
function asText(output) {
  if (typeof output === "string") return output;
  if (output === undefined) return "";
  try {
    return JSON.stringify(output) ?? String(output);
  } catch {
    return String(output);
  }
}

// setup receives the context once and registers the hook; what it returns is
// treated as a dispose callback, so it must return nothing. The hooks run from
// the project directory, which 2.x carries on ctx.location.
export default {
  id: "10x-hooks",
  setup: (ctx) => {
    const cwd = ctx.location?.directory ?? ctx.directory ?? process.cwd();
    ctx.tool.hook("execute.after", (event) => afterTool(event, cwd));
  },
};

// Direct invocation (node or bun): one event on stdin, the tool output the
// model would read on stdout. This is what test-hooks.sh --harness opencode
// drives; OpenCode itself imports the module and never reaches this branch.
let direct = false;
try {
  direct = realpathSync(process.argv[1] ?? "") === SELF;
} catch {
  direct = false;
}
if (direct) {
  const stdin = JSON.parse(readFileSync(0, "utf8"));
  const event = {
    tool: stdin.tool,
    input: stdin.input ?? stdin.args,
    result: { output: stdin.output ?? "" },
  };
  await afterTool(event, process.cwd());
  const parts = event.result.content ?? [{ type: "text", text: asText(event.result.output) }];
  process.stdout.write(parts.map((part) => part.text ?? "").join("\n\n"));
}
